version: "3.6"
services:   
    premium-demo:
        container_name: premium-demo
        ports:
            - 8000:80
        environment:
            - "ASPNETCORE_URLS=http://+"
        build:
            context: ./Premium-demo
        restart: on-failure 

    spa:
        container_name: spa
        ports:
            - 7000:80
        environment:
            - "ASPNETCORE_URLS=http://+"
        build:
            context: ./SPA     
        restart: on-failure    